############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About"
pageRef = "/about"
weight = 2


[[main]]
weight = 3
name="PhD projects"
pageRef = "/projects"


[[main]]
weight = 4
name="Events"
pageRef = "/events"

[[main]]
weight = 5
name = "People"
pageRef = "/people"

[[main]]
weight = 6
name="Consortium"
pageRef = "/consortium"

[[main]]
weight = 7
name="Contact"
pageRef="/contact"

[[main]]
weight = 8
name = "Internal"
pageRef = "https://kuleuven.sharepoint.com/sites/T0006414/SitePages/Home.aspx"

# footer menu

[[footer]]
name = "About"
pageRef = "/about"

[[footer]]
name = "Funding"
pageRef = "/funding"

[[footer]]

name="Impressum"
